import React from 'react';

const FAQItem: React.FC<{ question: string; answer: string }> = ({ question, answer }) => (
  <div className="border-b border-white/5 py-6">
    <h3 className="text-lg font-semibold text-white mb-2">{question}</h3>
    <p className="text-slate-400 text-sm leading-relaxed">{answer}</p>
  </div>
);

export const FAQ: React.FC = () => {
  const faqs = [
    {
      question: "Is the branding accurate?",
      answer: "Yes. Our Product Accuracy Engine specifically analyzes your product images to ensure logos, colors, and text are preserved and correctly represented in the generated ads."
    },
    {
      question: "Can I use my own images?",
      answer: "Absolutely. You can upload your own product photography as a base, or simply provide a URL and we'll scrape the best images to use."
    },
    {
      question: "How long does generation take?",
      answer: "Image ads are generated in under 30 seconds. Video ads (UGC, VFX) typically take 2-5 minutes depending on complexity."
    },
    {
      question: "Can I resell these ads?",
      answer: "Yes, you have full commercial rights to all assets generated by our platform. They are yours to use for your own campaigns or your clients."
    },
    {
      question: "Is this safe for ad platforms?",
      answer: "Yes. The content is generated to comply with standard advertising guidelines for Meta, TikTok, and Google Ads."
    }
  ];

  return (
    <section id="faq" className="py-24 bg-background">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold text-white mb-4">Frequently Asked Questions</h2>
        </div>
        <div className="space-y-2">
          {faqs.map((faq, index) => (
            <FAQItem key={index} question={faq.question} answer={faq.answer} />
          ))}
        </div>
      </div>
    </section>
  );
};